- name: Four In A Row
  android: https://play.google.com/store/apps/details?id=com.outofthebit.fourinarow
  ios: https://itunes.apple.com/app/four-in-a-row-2013/id604921715
  icon: fourinarow.png

- name: Dots And Boxes
  android: https://play.google.com/store/apps/details?id=com.outofthebit.dots&hl=en
  ios: https://itunes.apple.com/app/dots-and-boxes-2013/id625311640
  icon: dotsandboxes.png

- name: SoundRide
  android: https://play.google.com/store/apps/details?id=com.outofthebit.soundride&hl=en
  ios: https://itunes.apple.com/cz/app/sound-ride/id695116156
  icon: soundride.png

- name: Laser Maze
  android: https://play.google.com/store/apps/details?id=fr.OwlGames.LaserMaze
  icon: lasermaze.png

- name: 2048
  android: https://play.google.com/store/apps/details?id=org.cocos2dx.OwlGames_2048
  icon: 2048.png


